// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// readSvmLight
SEXP readSvmLight(SEXP fname);
RcppExport SEXP sparsity_readSvmLight(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    SEXP fname = Rcpp::as<SEXP >(fnameSEXP);
    SEXP __result = readSvmLight(fname);
    return Rcpp::wrap(__result);
END_RCPP
}
// writeSvmLight
SEXP writeSvmLight(SEXP sparseMatrix, SEXP labelVector, SEXP fname);
RcppExport SEXP sparsity_writeSvmLight(SEXP sparseMatrixSEXP, SEXP labelVectorSEXP, SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    SEXP sparseMatrix = Rcpp::as<SEXP >(sparseMatrixSEXP);
    SEXP labelVector = Rcpp::as<SEXP >(labelVectorSEXP);
    SEXP fname = Rcpp::as<SEXP >(fnameSEXP);
    SEXP __result = writeSvmLight(sparseMatrix, labelVector, fname);
    return Rcpp::wrap(__result);
END_RCPP
}
