# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readSvmLight <- function(fname) {
    .Call('sparsity_readSvmLight', PACKAGE = 'sparsity', fname)
}

writeSvmLight <- function(sparseMatrix, labelVector, fname) {
    .Call('sparsity_writeSvmLight', PACKAGE = 'sparsity', sparseMatrix, labelVector, fname)
}

