# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

liblinearTrain <- function(inputMatrix, labels, solver_type, cost, epsilon) {
    .Call('sparsity_liblinearTrain', PACKAGE = 'sparsity', inputMatrix, labels, solver_type, cost, epsilon)
}

#' Reads a sparse matrix from a SVMlight compatible file
#' @param fileName input file name
#' @return list with a sparse matrix and a list of labels
readSvmLight <- function(filename) {
    .Call('sparsity_readSvmLight', PACKAGE = 'sparsity', filename)
}

#' Writes a sparse matrix to a SVMlight compatible file
#'
#' @param inputMatrix sparse matrix
#' @param labels list of numeric labels for each row in the matrix 
#' @param fileName  output file name
#' @return list with debug information
writeSvmLight <- function(inputMatrix, labels, fileName) {
    .Call('sparsity_writeSvmLight', PACKAGE = 'sparsity', inputMatrix, labels, fileName)
}

